// src/routes/ResumeExperienceItem.svelte
<script lang="ts">
	export let workplace: string = '';
	export let workplaceLink: string = '';
	export let location: string = '';
	export let startTime: string = '';
	export let endTime: string = '';
	export let position: string = '';
	export let descriptions: Array<string> = [];
</script>

<div>
	<a href={workplaceLink}><b>{workplace}</b></a>{#if location}<span>, {location}</span>{/if}
	<ul>
		{#if startTime}<li>{startTime} – {endTime}</li>{/if}
		{#if position}<li><i>{position}</i></li>{/if}
		{#each descriptions as desc (desc)}
			<li>
				– {desc}
			</li>
		{/each}
	</ul>
</div>

<style>
	ul {
		margin-top: 1em;
		margin-bottom: 1em;
	}
</style>

// src/components/ResumeExperienceItem.vue
<template>
<p>
  <a :href="workplaceLink"><b>{{workplace}}</b></a><span v-if="location">, {{location}}</span>
  <ul>
      <li v-if="startTime">{{startTime}} – {{endTime}}</li>
      <li v-if="position"><i>{{position}}</i></li>
      <li v-for="desc in descriptions" :key="desc">
          – {{desc}}
      </li>
  </ul>
</p>
</template>

<script>
export default {
  props: {
    workplace: {
      type: String,
      default: ''
    },
    workplaceLink: {
      type: String,
      default: ''
    },
    location: {
      type: String,
      default: ''
    },
    startTime: {
      type: String,
      default: ''
    },
    endTime: {
      type: String,
      default: ''
    },
    position: {
      type: String,
      default: ''
    },
    descriptions: {
      type: Array,
      default: function() {
        return []
      }
    }
  }
}
</script>
